musei/urls.py
from django.urls import path
from musei.views import homepage, museoDetailView, autoreDetailView

app_name="musei"
urlpatterns = [
    path('', homepage, name='homepage'),
    path('musei/<int:pk>', museoDetailView, name="dettagli_museo"),
    path('autori/<int:pk>', autoreDetailView, name="dettagli_autore"),
]

progetto_maturita/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import MyLoginView, index_root
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('musei.urls', namespace='musei')),
    path('', index_root, name='homepage'),
    path('accounts/login/', MyLoginView.as_view(), name='login'),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

musei/models.py
from django.db import models

# Create your models here.
class Museo(models.Model):
    nome= models.CharField(max_length=50)
    citta= models.CharField(max_length=20)
    stato= models.CharField(max_length=20)

    def __str__(self):
        return self.nome
    
    class Meta:
        verbose_name="Museo"
        verbose_name_plural="Musei"
    
    
class Autore(models.Model):
    nome= models.CharField(max_length=20)
    cognome= models.CharField(max_length=20)
    annoNascita= models.CharField(max_length=4)
    annoMorte= models.CharField(max_length=4)
    biografia= models.TextField()

    def __str__(self):
        return self.nome + " " + self.cognome
    
    class Meta:
        verbose_name="Autore"
        verbose_name_plural="Autori"
    
class Opera(models.Model):
    img= models.ImageField(upload_to='images/')
    nomeOp= models.CharField(max_length=50)
    anno= models.CharField(max_length=4)
    tipo= models.CharField(max_length=10)
    materiale= models.CharField(max_length=30)
    autore= models.ForeignKey(Autore, on_delete=models.CASCADE, related_name="opere")
    museo= models.ForeignKey(Museo, on_delete=models.CASCADE, related_name="opere")

    def __str__(self):
        return self.nomeOp
    
    class Meta:
        verbose_name="Opera"
        verbose_name_plural="Opere"

musei/views.py
from django.shortcuts import render, get_object_or_404
from .models import Museo,Opera,Autore

# Create your views here.
def homepage(request):
    musei= Museo.objects.all() 

    context={"musei":musei}
    print (context)
    return render(request, "homepage.html", context)

def museoDetailView(request,pk):
    museo=get_object_or_404(Museo, pk=pk)
    opere=Opera.objects.filter(museo_id=pk)
    context={"museo": museo,
             "opere": opere}
    return render(request, "dettagli_museo.html", context)

def autoreDetailView(request,pk):
    autore=get_object_or_404(Autore, pk=pk)
    context={"autore": autore}
    return render(request, "dettagli_autore.html", context)

progetto_maturita/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy

# Create your views here.
class MyLoginView(LoginView):
    def get_success_url(self):
        return reverse_lazy('homepage')  # Reindirizza alla homepage dopo il login

def index_root(request):
    return render(request, "index_root.html")

musei/templates/dettagli_autore.html
{% extends "base.html" %}

{%block title%} {{autore.nome}} {{autore.cognome}}{%endblock title%}

{%block content%}
    <h1>{{autore.nome}} {{autore.cognome}}</h1> <br>
    <h4>Nato il {{autore.annoNascita}}, Morto il {{autore.annoMorte}}</h4>
    <h5>Biografia: {{autore.biografia}}</h5>

{%endblock content%}

musei/templates/dettagli_museo.html
{% extends "base.html" %}

{%block title%} {{museo.nome}} {%endblock title%}

{%block content%}
    <h1>{{museo.nome}}</h1> <br>
    <h3>{{museo.citta}}, {{museo.stato}}</h3>
    <h5>Opere importanti: </h5>
    {%for opera in opere%}
        <h2><strong>{{opera.nomeOp}}</strong></h2> <br>
        <img src="{{ opera.img.url }}" alt="{{ opera.nomeOp }}" /> <br>
        <p><a href={%url 'musei:dettagli_autore' opera.autore.id%}>{{opera.autore}}</a>, {{opera.anno}}, {{opera.tipo}} {{opera.materiale}}</p>
        <hr>
    {% endfor %}

{%endblock content%}

musei/templates/homepage.html
{% extends "base.html" %}

{%block title%} Musei {%endblock title%}

{%block content%}
    <h2>Musei:</h2>
    {%for museo in musei%}
        <p>
            <strong><a href="/musei/{{museo.id}}">{{museo.nome}}</a></strong> <br>
            <strong>{{museo.citta}}</strong> <br>
            <strong>{{museo.stato}}</strong> <br>
        </p>

        <hr>
    {% endfor %}

{%endblock content%}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="it">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>{% block title %} Musei {% endblock title %}</title>
</head>
<body>
    <nav class="navbar navbar-light" style="background-color: #dda0dd;">
        <a class="navbar-brand" href="#">MUSEUM COLLECTING</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Gallery
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/">Homepage</a>
                </div>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ request.user.username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {% if request.user.is_superuser %}
                    <a class="dropdown-item" href="/admin/">Admin Panel</a>
                    <div class="dropdown-divider"></div>
                  {% endif %}
                  <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </div>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>
      <div class="container my-4">
        {%block content%}
        {%endblock content%}

        {%block script%}
        {%endblock script%}
      </div>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>

templates/index_root.html
{% extends "base.html" %}

{%block title%} {{block.super}} | Index root {%endblock title%}

{%block content%}
    <ol>
        <li><a href="/admin">Pannello admin</a></li>
        <li><a href="{% url 'musei:homepage'%}">Index news</a></li>
    </ol>

{%endblock content%}